songSearch/songSearch/urls.py
from django.contrib import admin
from django.urls import path, include
import xadmin

from songcommon import views

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('',views.home),
    # 搜索
    # path(r'search', include('haystack.urls',namespace='haystack')),
    path(r'search/', include('songcommon.urls',namespace='haystack')),

    # 歌曲
    path(r'searchSong/',include('songcommon.urls', namespace='song')),
    path(r'song/',include('songapp.urls',namespace='songapp'))

]

songSearch/songapp/urls.py
# encoding: utf-8
'''
@license: (C) Copyright 2018-2017, Node Supply Chain Manager Corporation Limited.
@contact: 1257309054@qq.com
@file: urls.py
@time: 2018/8/13 16:09
@author:LDC
'''


from django.urls import path, include
from songapp import views

app_name ='songapp'

urlpatterns = (
    # 添加路由
    path(r'login',views.login,name='login'),

)

songSearch/songcommon/urls.py
# encoding: utf-8
'''
@license: (C) Copyright 2018-2017, Node Supply Chain Manager Corporation Limited.
@contact: 1257309054@qq.com
@file: urls.py
@time: 2018/8/13 16:08
@author:LDC
'''

from django.urls import   path

from songcommon import views
from songcommon.searchView import MySearchView

app_name ='songcommon'

urlpatterns = (
    path(r'<int:sid>', views.search_song, name='search_song'),
    path(r'search/?', MySearchView.as_view(), name='haystack_search'),

)

songSearch/songapp/models.py
from django.db import models

# Create your models here.

songSearch/songcommon/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

# 评论表
class Comment(models.Model):
    id = models.IntegerField(primary_key=True)
    uid = models.IntegerField(verbose_name='用户id')
    sid = models.IntegerField(verbose_name='歌曲id')
    content = models.TextField(verbose_name='评论内容')
    replynum = models.IntegerField(db_column='replyNum', blank=True, null=True,verbose_name='回复数量')  
    likenum = models.IntegerField(db_column='likeNum', blank=True, null=True,verbose_name='点赞数量')  
    createtime = models.DateTimeField(db_column='createTime',auto_now_add=True, blank=True, null=True,verbose_name='创建时间')  
    isdelete = models.IntegerField(db_column='isDelete', blank=True, null=True,verbose_name='是否删除')  
    replyid = models.IntegerField(db_column='replyId', blank=True, null=True,verbose_name='回复哪条评论id')  

    class Meta:
        managed = False
        db_table = 'Comment'

# 歌曲表
class Song(models.Model):
    sid = models.AutoField(primary_key=True,verbose_name='歌曲编号')
    name = models.CharField(max_length=100,verbose_name='歌名')
    singer = models.CharField(max_length=100, blank=True, null=True,verbose_name='歌手')
    lyric = models.TextField(blank=True, null=True,verbose_name='歌词')
    url = models.TextField(verbose_name='歌曲url')
    songdata = models.TextField(db_column='songData', blank=True, null=True,verbose_name='歌曲文件')
    likenum = models.IntegerField(db_column='likeNum', blank=True, null=True,verbose_name='点赞数')
    playnum = models.IntegerField(db_column='playNum', blank=True, null=True,verbose_name='播放量')
    commentnum = models.IntegerField(db_column='commentNum', blank=True, null=True,verbose_name='评论数')
    iscopyright = models.IntegerField(db_column='isCopyright', blank=True, null=True,verbose_name='版权信息')
    quality = models.CharField(max_length=10, blank=True, null=True,verbose_name='音质')
    typeid = models.IntegerField(db_column='typeId', blank=True, null=True,verbose_name='歌曲类型id')
    originid = models.IntegerField(db_column='originId', blank=True, null=True,verbose_name='歌曲来源id')

    class Meta:
        managed = False
        db_table = 'Song'
        ordering = ['-playnum', ]
        unique_together = (('name', 'singer', 'originid'),)

# 歌曲来源表
class Songorigin(models.Model):
    originid = models.IntegerField(db_column='originId', primary_key=True,verbose_name='歌曲来源id')
    origin = models.CharField(max_length=10,verbose_name='来源')
    isdelete = models.IntegerField(db_column='isDelete', blank=True, null=True,verbose_name='是否删除')

    class Meta:
        managed = False
        db_table = 'SongOrigin'

# 歌曲分类表
class Songtype(models.Model):
    typeid = models.IntegerField(db_column='typeId', primary_key=True,verbose_name='歌曲分类id')
    type = models.CharField(max_length=10,verbose_name='歌曲类型')
    isdelete = models.IntegerField(db_column='isDelete', blank=True, null=True,verbose_name='是否删除')

    class Meta:
        managed = False
        db_table = 'SongType'

# 用户信息表
class User(models.Model):
    uid = models.AutoField(primary_key=True,verbose_name='用户id')
    name = models.CharField(db_column='NAME', unique=True, max_length=20,verbose_name='用户名')
    password = models.CharField(db_column='PASSWORD', max_length=32,verbose_name='密码')
    level = models.IntegerField(db_column='LEVEL', blank=True, null=True,verbose_name='等级')
    phone = models.IntegerField(verbose_name='手机号')
    icon = models.ImageField(blank=True, null=True,verbose_name='头像')
    signature = models.CharField(max_length=200, blank=True, null=True,verbose_name='签名')
    isdelete = models.IntegerField(db_column='isDelete', blank=True, null=True,verbose_name='是否删除')
    createtime = models.DateTimeField(db_column='createTime',auto_now_add=True, blank=True, null=True,verbose_name='创建时间')
    createid = models.IntegerField(db_column='createId', blank=True, null=True,verbose_name='创建人id')
    modifytime = models.DateTimeField(db_column='modifyTime', blank=True, null=True,verbose_name='修改时间')
    modifyid = models.IntegerField(db_column='modifyId', blank=True, null=True,verbose_name='修改人id')
    issilent = models.IntegerField(db_column='isSilent', blank=True, null=True,verbose_name='是否禁言')

    class Meta:
        managed = False
        db_table = 'User'

# 用户与歌曲关系表
class UserToSong(models.Model):
    id = models.IntegerField(primary_key=True,verbose_name='id')
    uid = models.IntegerField(blank=True, null=True,verbose_name='用户id')
    sid = models.IntegerField(blank=True, null=True,verbose_name='歌曲id')
    playtime = models.DateTimeField(db_column='playTime', auto_now_add=True,blank=True, null=True,verbose_name='播放时间')
    iscollect = models.IntegerField(db_column='isCollect', blank=True, null=True,verbose_name='是否收藏')
    playcount = models.IntegerField(db_column='playCount', blank=True, null=True,verbose_name='播放次数')
    iscomment = models.IntegerField(db_column='isComment', blank=True, null=True,verbose_name='评论次数')

    class Meta:
        managed = False
        db_table = 'User_to_Song'

# 用户与用户关系表
class UserToUser(models.Model):
    uid = models.IntegerField(verbose_name='用户id')
    attentionuid = models.IntegerField(db_column='attentionUid',verbose_name='被关注的用户id')
    isdelete = models.IntegerField(db_column='isDelete', blank=True, null=True,verbose_name='是否删除')

    class Meta:
        managed = False
        db_table = 'User_to_User'

songSearch/songapp/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return None

songSearch/songcommon/views.py
from django.core.cache import cache
from django.http import HttpResponse
from django.shortcuts import render

from songcommon.models import Song
from songcommon.utils import get_url




def home(request):
    return render(request,'search/search.html',context={'search_method':'songname'})



def search_song(request,sid):
    s = Song.objects.get(sid=sid)
    # print('********',s)
    # print('===========',s.url)
    # print(get_url(s.url))

    s.playnum += 1
    s.save()
    # print(s.lyric.split('\n'))
    back_url = cache.get('host:' + request.get_host() + 'url')

    context = {'name':s.name,'url': get_url(s.url),'lyrics':s.lyric.split('\n'),'back_url':back_url}
    return render(request, 'search/song.html',context=context)

songSearch/songapp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>搜音乐</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/new_file.css' %}"/>
	</head>
	<html>
		<body class="Bigbox">
			<!--头部-->
			<div class="nav">

				<img class="logo" src="{% static 'img/logo.jpg' %}"/>

				<div class="nav1">
					<ul>
						<li><a href="#">&nbsp;&nbsp;&nbsp;首页&nbsp;&nbsp;&nbsp;</a></li>
						<li><a href="#">全网推荐</a></li>
						<li><a href="#">每周排行</a></li>
						<li><a href="#">播放历史</a></li>
                        <li><a href="#">新歌推荐</a></li>
						<li><a href="#">个人收藏</a></li>
						<li><a href="#">联系客服</a></li>
                        <li class="register"><a href="#">注册</a></li>
						<li class="login"><a href="#">登陆</a></li>

					</ul>
				</div>
			</div>

            <div id="page" class="old">
                <div id="wrapper">
                    <div class="title18_search">
                        <h2>嘤嘤嘤&音乐搜索</h2>
                        <div class="search_tab" data-spm="23309985">
                            <ul>
                                <li><a class="current" href="javascript:;" title=""><span>全部</span></a></li>
                                <li><a href="#" title="歌曲"><span>歌曲</span></a></li>
                                <li><a href="#" title="专辑"><span>专辑</span></a></li>
                                <li><a href="#" title="艺人"><span>艺人</span></a></li>
                                <li><a href="#" title="歌词"><span>歌词</span></a></li>
                                <li><a href="#" title="歌单"><span>歌单</span></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="more_cols clearfix">
                        <div class="more_cols_left">
                            <div class="more_cols_left_inner">
                                <div class="search_box" data-spm="23309989">
                                    <form class="big_search_form" name="searchindex" id=""
                                          action="#" method="get" autocomplete="off"
                                          onsubmit="search_focus();">
                                        <input class="big_search grey" type="text" id="search_text" name="key"
                                               title="搜索您感兴趣的专辑/歌曲/艺人" value="&nbsp;&nbsp;&nbsp;搜索您感兴趣的专辑/歌曲/艺人"
                                               onfocus="search_focus('click');" onblur="search_focus('blur');">
                                        <input class="big_search_bt" type="submit" value="搜索" id="musicsearch">
                                    </form>
                                    <span class="hints">支持拼音首字母搜索。如搜索“刘德华”输入“ldh”即可。</span>
                                </div>
                                <input type="hidden" name="tour_name" value="" id="tour_name">

                            </div>
                        </div>
                        <!--<div class="chnl_right" data-spm="23309993">-->

                            <!--<div class="add2xiami_bt">-->
                                <!--<p>-->
                                    <!--<a href="//www.xiami.com/wiki/addalbum" title="">添加虾米还没有的专辑</a>-->
                                <!--</p>-->
                                <!--<p>-->
                                    <!--<a href="//www.xiami.com/wiki/addartist" title="">添加虾米还没有的艺人</a>-->
                                <!--</p>-->
                            <!--</div>-->

                            <!--<div class="add2xiami_bt">-->
                                <!--<p>-->
                                    <!--<a href="//www.xiami.com/song/tag/" title="">查看标签为的歌曲</a>-->
                                <!--</p>-->
                                <!--<p>-->
                                    <!--<a href="//www.xiami.com/artist/tag/" title="">查看标签为的艺人</a>-->
                                <!--</p>-->
                            <!--</div>-->

                            <!--<div id="search_relate_musician" style="display:none;">-->
                                <!--<h4>你可能会感兴趣的音乐人</h4>-->
                                <!--<div class="common_sec">-->
                                    <!--<ul id="related_musician"></ul>-->
                                <!--</div>-->
                            <!--</div>-->
                            <!--<div id="hot_events_show" class="blank30">-->

                                <!--<style>-->
                                    <!--#hot_events_show {-->
                                        <!--position: relative;-->
                                        <!--margin-left: 5px;-->
                                        <!--margin-right: 5px;-->
                                    <!--}-->

                                    <!--#hot_events_show h3 {-->
                                        <!--padding-top: 15px;-->
                                        <!--font-size: 14px;-->
                                        <!--line-height: 30px;-->
                                    <!--}-->

                                    <!--.past_collect_itemA {-->
                                        <!--border: none;-->
                                        <!--padding: 4px 0;-->
                                    <!--}-->

                                    <!--#hot_events_show .acts {-->
                                        <!--position: absolute;-->
                                        <!--right: 0;-->
                                        <!--top: 22px;-->
                                    <!--}-->
                                <!--</style>-->

                            <!--</div>-->
                        <!--</div>-->

                    </div>
                </div>
                <!--content end-->
            </div>

            <!--底部-->
            <div id="footer" data-spm="1110930425">
                <div class="gap">
                    <div class="wrapper">
                        <div class="content">
                            <div class="sitemap">

                                <dl>
                                    <dt>关于</dt>
                                    <dd><a title="关于我们" href="#">关于我们</a></dd>
                                    <dd><a title="独立音乐人合作" href="#" target="_blank">独立音乐人合作</a>
                                    </dd>
                                    <dd><a title="联系我们" href="#">联系我们</a></dd>
                                    <dd><a title="友情链接" href="#">友情链接</a></dd>
                                    <dd><a title="知识产权声明及隐私权政策"
                                           href="#">知识产权声明及隐私权政策</a>
                                    </dd>
                                </dl>

                                <dl>
                                    <dt>音音音客户端</dt>
                                    <dd><a title="虾米 for iPhone" href="#">嘤嘤嘤 for
                                        iPhone</a><sup class="hot"></sup></dd>
                                    <dd><a title="虾米 for Android" href="#">嘤嘤嘤 for Android</a>
                                    </dd>
                                    <dd><a title="虾米 for Windows" href="#">嘤嘤嘤 for Windows</a>
                                    </dd>
                                    <dd><a title="虾米 for Mac" href="#">嘤嘤嘤 for Mac</a></dd>
                                    <dd><a title="虾米 for iPad" href="#">嘤嘤嘤 for iPad</a></dd>
                                </dl>


                                <dl>
                                    <dt>更多</dt>
                                    <dd><a title="分类找歌" href="#">分类找歌</a></dd>
                                    <dd><a title="帮助中心" href="#">帮助中心</a></dd>
                                    <dd><a title="音频上传" href="#">音频上传</a></dd>
                                    <dd><a title="MV上传" href="#">MV上传</a></dd>
                                    <dd><a title="添加歌词" href="#">添加歌词</a></dd>
                                </dl>
                            </div>

                            <div class="cooperation">
                            </div>

                        </div>

                        <div class="extra">
                            <div class="sns">
                                <a href="#" title="新浪微博"><b
                                        class="icon sina"></b></a>
                                <a href="#" title="人人网"><b class="icon renren"></b></a>
                                <a href="#" title="QQ 空间"><b class="icon qzone"></b></a>
                                <a href="#" title="腾讯微博"><b class="icon tqq"></b></a>
                                <a href="#" title="豆瓣"><b class="icon douban"></b></a>
                            </div>

                            <div class="copyright">© 2007 -
                                <script>document.write(new Date().getFullYear());</script>
                                2018 <a href="#">广州嘤嘤嘤音乐科技有限公司</a> - <a href="#"
                                                                                        title="网站地图">网站地图</a> <br><a
                                        href="#" target="_blank">浙网文[2018]3192-218号</a>&nbsp;&nbsp;&nbsp;&nbsp;<a
                                        href="#" target="_blank" title="粤ICP备08103200号-2">粤ICP备08103200号-2</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </html>
</html>

songSearch/songcommon/templates/search/search.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>搜音乐</title>
    <link rel="stylesheet" type="text/css" href="/songstatic/css/new_file.css"/>
    <link rel="stylesheet" type="text/css" href="/songstatic/css/bootstrap.min.css"/>
</head>
    <body class="Bigbox" style="height: 400px;width: 1000px;margin: 0 auto;">
        <!--头部-->
        <div class="nav">

            <img class="logo" src="{% static 'img/logo.jpg' %}"/>

            <div class="nav1">
                <ul>
                    <li><a href="#">&nbsp;&nbsp;&nbsp;首页&nbsp;&nbsp;&nbsp;</a></li>
                    <li><a href="#">全网推荐</a></li>
                    <li><a href="#">播放历史</a></li>
                    <li><a href="#">个人收藏</a></li>
                    <li class="register"><a href="#">注册</a></li>
                    <li class="login"><a href="#">登陆</a></li>
                </ul>
            </div>
        </div>
        <div class="more_cols clearfix">
        <div class="more_cols_left">
            <div class="more_cols_left_inner">
                <div class="search_box" data-spm="23309989">
                    <form class="big_search_form" name="searchindex"
                          action="{% url 'haystack:haystack_search' %}" method="get"
                          >

                            {% ifequal search_method 'songname'  %}
                                <select name="search-method" style="width: 70px;height:35px;margin-left: 50px;padding: 0">
                                    <option selected>歌名</option>
                                    <option >歌手</option>
                                    <option >歌词</option>
                                </select>
                            {% endifequal %}

                            {% ifequal search_method 'singer' %}
                                <select name="search-method" style="width: 70px;height:35px;margin-left: 100px;padding: 0">
                                    <option >歌名</option>
                                    <option selected>歌手</option>
                                    <option >歌词</option>
                                </select>
                            {% endifequal %}
                            {% ifequal search_method 'lyric' %}
                                <select name="search-method" style="width: 70px;height:35px;margin-left: 100px;padding: 0">
                                    <option >歌名</option>
                                    <option >歌手</option>
                                    <option selected>歌词</option>
                                </select>
                            {% endifequal %}

                        <input class="big_search grey" type="text" id="search_text" name="q" style="margin-left: 0"
                               title="喜欢就搜搜吧" placeholder="&nbsp;&nbsp;&nbsp;搜索您感兴趣的专辑/歌曲/艺人"
                               onfocus="search_focus('click');" onblur="search_focus('blur');">
                        <input class="big_search_bt" type="submit" value="搜索" id="musicsearch">
                    </form>
                    <span class="hints">左边下拉框可以选择歌词或者歌手搜索</span>
                    <div class="found-result" style="width: 800px;height:200px;overflow: auto;margin: 10px auto;margin-left: 100px">
                        {% if query %}

                            {% ifequal search_method 'lyric' %}
                                {% for result in object_list %}
                                    {% ifequal no_whoosh 'no_whoosh'%}
                                        播放:{{ result.playnum }}&nbsp; &nbsp;&nbsp;
                                        评论:{{ result.commentnum }}&nbsp;&nbsp;&nbsp;

                                        <a href="{% url 'song:search_song' result.sid %}  " target="_self">{{ result.name }} {{ result.singer }}</a> <br/>
                                    {% else %}
                                        播放:{{ result.object.playnum }}&nbsp; &nbsp;&nbsp;
                                        评论:{{ result.object.commentnum }}&nbsp;&nbsp;&nbsp;
                                        <a href="{% url 'song:search_song' result.object.sid %}  " target="_self">{{ result.object.name }} {{ result.object.singer }}</a><br/>

                                    {% endifequal %}

                                    {% empty %}
                                    <p>试下输入歌手或者歌名搜索吧！！！</p>


                                {% endfor %}

                                {% else %}
                                <div style="height: 60px;">
                                    {% for result in object_list %}
                                        播放:{{ result.playnum }}&nbsp; &nbsp;&nbsp;
                                        评论:{{ result.commentnum }}&nbsp;&nbsp;&nbsp;

                                        <a href="{% url 'song:search_song' result.sid %}  " target="_self">{{ result.name }} {{ result.singer }}</a><br/>

                                        {% empty %}
                                        <p>试下左边的下拉框选择歌词搜索吧！！！</p>

                                    {% endfor %}
                                </div>
                            {% endifequal %}

{#                            {% if page.has_previous or page.has_next %}#}
{#                                <div>#}
{#                                    {% if page.has_previous %}#}
{#                                        <a href="?q={{ query }}&page={{ page.previous_page_number }}">#}
{#                                    {% endif %}#}
{#                                    « 上一页#}
{#                                    {% if page.has_previous %}#}
{#                                        </a>#}
{#                                    {% endif %}#}
{#                                |#}
{#                                    {% if page.has_next %}#}
{#                                        <a href="?q={{ query }}&page={{ page.next_page_number }}">#}
{#                                    {% endif %}下一页 »{% if page.has_next %}#}
{#                                    </a>#}
{#                                {% endif %}#}
{#                                </div>#}
{#                            {% endif %}#}
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>

    </body>
</html>

songSearch/songcommon/templates/search/song.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>

</head>
<body>
    <div style="width: 600px;margin: 0 auto;height: 400px;">
        <h1>{{ name }}</h1>
    <audio src="{{ url }}" type="video/mp4" controls="controls" autoplay='autoplay' loop="loop" preload='preload'>
{#        <audio id="audio" src="{{ url }}" type="video/mp4" controls="" autoplay='' loop="loop" preload=''>#}
        </audio>
        <br>
        <div style="height:400px;overflow: auto">
        {% for lyric in lyrics %}
            {{ lyric }}
            <br>
        {% endfor %}
        </div>

    <a href="http://{{ back_url }}" target="_self">返回</a>

    </div>
</body>
<script src="/songstatic/js/playsong.js"></script>

</html>